/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <pcre.h>
#include "osxVolumeTable.h"
#include "log.h"
#include "command.h"
#include "util.h"

#define OVECCOUNT 30

/** Initializes the osxVolumeTable module */
void
init_osxVolumeTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_osxVolumeTable();
}

static struct timeval volume_cache_timestamp = { 0, 0 };
static int last_index_used = 0;

/** Initialize the osxVolumeTable table by defining its contents and how it's structured */
void
initialize_table_osxVolumeTable(void)
{
    static oid osxVolumeTable_oid[] = {1,3,6,1,4,1,20038,2,1,3,1};
    size_t osxVolumeTable_oid_len   = OID_LENGTH(osxVolumeTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "osxVolumeTable",     osxVolumeTable_handler,
              osxVolumeTable_oid, osxVolumeTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: osxVolumeIndex */
                           0);
    table_info->min_column = COLUMN_OSXVOLUMEINDEX;
    table_info->max_column = COLUMN_OSXVOLUMECAPACITY;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = osxVolumeTable_get_first_data_point;
    iinfo->get_next_data_point  = osxVolumeTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct osxVolumeTable_entry {
    /* Index values */
    long osxVolumeIndex;

    /* Column values */
    char *osxVolumeFilesystem;
    size_t osxVolumeFilesystem_len;
    char *osxVolumeMountpoint;
    size_t osxVolumeMountpoint_len;
    u_long osxVolumeSize;
    u_long osxVolumeUsed;
    u_long osxVolumeAvail;
    u_long osxVolumeCapacity;
    
    /* Obsolescence checking */
    time_t last_seen;

    /* Illustrate using a simple linked list */
    int   valid;
    struct osxVolumeTable_entry *next;
};

struct osxVolumeTable_entry  *osxVolumeTable_head;

/* create a new row in the (unsorted) table */
struct osxVolumeTable_entry *
osxVolumeTable_createEntry(
                 long  osxVolumeIndex) {
    struct osxVolumeTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct osxVolumeTable_entry);
    if (!entry)
        return NULL;

    entry->osxVolumeIndex = osxVolumeIndex;
    entry->next = osxVolumeTable_head;
    osxVolumeTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
osxVolumeTable_removeEntry( struct osxVolumeTable_entry *entry ) {
    struct osxVolumeTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = osxVolumeTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        osxVolumeTable_head = ptr->next;
    else
        prev->next = ptr->next;
        
    if (entry->osxVolumeFilesystem) free (entry->osxVolumeFilesystem);
    if (entry->osxVolumeMountpoint) free (entry->osxVolumeMountpoint);

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
osxVolumeTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = osxVolumeTable_head;
    return osxVolumeTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
osxVolumeTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct osxVolumeTable_entry *entry = (struct osxVolumeTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->osxVolumeIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


void update_volumes()
{
  struct timeval now;
  gettimeofday(&now, NULL);
  
  char *data = x_command_run("df -m", 0);
  if (!data) return;
  size_t data_len = strlen(data);

  const char *error;
  int erroffset;
  int ovector[OVECCOUNT];
  pcre *re = pcre_compile("^(.*)[ ]+(\\d+)[ ]+(\\d+)[ ]+(\\d+)[ ]+(\\d+)%[ ]+(.*)$", PCRE_MULTILINE, &error, &erroffset, NULL);
  if (re == NULL) { x_printf ("update_ram failed to compile regex for wired"); free (data); return; }

  ovector[0] = 0;
  ovector[1] = 0;
  while(1)
  {
    int options = 0;                 /* Normally no options */
    int start_offset = ovector[1];   /* Start at end of previous match */
    
    if (ovector[0] == ovector[1])
    {
      if (ovector[0] == data_len) break;
    }

    int rc = pcre_exec(
      re,                   /* the compiled pattern */
      NULL,                 /* no extra data - we didn't study the pattern */
      data,              /* the subject string */
      data_len,       /* the length of the subject */
      start_offset,         /* starting offset in the subject */
      options,              /* options */
      ovector,              /* output vector for substring information */
      OVECCOUNT);           /* number of elements in the output vector */

    if (rc == PCRE_ERROR_NOMATCH)
    {
      if (options == 0) break;
      ovector[1] = start_offset + 1;
      continue;    /* Go round the loop again */
    }

    /* Other matching errors are not recoverable. */
    if (rc > 0)
    {
      /* Matched a volume 
       * 0=FullString 1(2)=Disk 2(4)=Size(blocks) 3(6)=Used 4(8)=Avail 5(10)=Percent 6(12)=Volume
       */
      char *volname_str;
      asprintf (&volname_str, "%.*s", ovector[13] - ovector[12], data + ovector[12]);
      trim_end(volname_str);
      
      struct osxVolumeTable_entry *entry = osxVolumeTable_head;
      while (entry)
      {
        if (!strcmp(volname_str, entry->osxVolumeMountpoint)) break;
        entry = entry->next;
      }
      if (!entry)
      {
        last_index_used++;
        entry = osxVolumeTable_createEntry(last_index_used);
        entry->osxVolumeMountpoint = strdup(volname_str);
        entry->osxVolumeMountpoint_len = strlen (entry->osxVolumeMountpoint);
      }
      entry->last_seen = now.tv_sec;
      free (volname_str);
      volname_str = NULL;
      if (entry->osxVolumeFilesystem) free (entry->osxVolumeFilesystem);
      asprintf (&entry->osxVolumeFilesystem, "%.*s", ovector[3] - ovector[2], data + ovector[2]);
      trim_end(entry->osxVolumeFilesystem);
      entry->osxVolumeFilesystem_len = strlen (entry->osxVolumeFilesystem);
      entry->osxVolumeSize = extract_uint_in_range(data + ovector[4], ovector[5] - ovector[4]);
      entry->osxVolumeUsed = extract_uint_in_range(data + ovector[6], ovector[7] - ovector[6]);
      entry->osxVolumeAvail = extract_uint_in_range(data + ovector[8], ovector[9] - ovector[8]);
      entry->osxVolumeCapacity = extract_uint_in_range(data + ovector[10], ovector[11] - ovector[10]);
    }
    else
    {
      x_printf("Matching error %d\n", rc);
      pcre_free(re);    /* Release memory used for the compiled pattern */
      return;
    }  
  }
  
  /* Check for obsolete entries */
  struct osxVolumeTable_entry *entry = osxVolumeTable_head;
  while (entry)
  {
    struct osxVolumeTable_entry *next = entry->next;
    if (entry->last_seen != now.tv_sec)
    {
      /* Entry is obsolete */
      osxVolumeTable_removeEntry(entry);
    }
    entry = next;
  }

  /* Update cache timestamp */
  gettimeofday(&volume_cache_timestamp, NULL);    
}

#define MAX_CACHE_TIMEOUT 10

void update_volumes_if_necessary()
{
  struct timeval now;
  gettimeofday(&now, NULL);
  if ((now.tv_sec - volume_cache_timestamp.tv_sec) > MAX_CACHE_TIMEOUT)
  { update_volumes(); }
}

/** handles requests for the osxVolumeTable table */
int
osxVolumeTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct osxVolumeTable_entry          *table_entry;

    update_volumes_if_necessary();

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct osxVolumeTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_OSXVOLUMEINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->osxVolumeIndex);
                break;
            case COLUMN_OSXVOLUMEFILESYSTEM:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->osxVolumeFilesystem,
                                          table_entry->osxVolumeFilesystem_len);
                break;
            case COLUMN_OSXVOLUMEMOUNTPOINT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->osxVolumeMountpoint,
                                          table_entry->osxVolumeMountpoint_len);
                break;
            case COLUMN_OSXVOLUMESIZE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->osxVolumeSize);
                break;
            case COLUMN_OSXVOLUMEUSED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->osxVolumeUsed);
                break;
            case COLUMN_OSXVOLUMEAVAIL:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->osxVolumeAvail);
                break;
            case COLUMN_OSXVOLUMECAPACITY:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->osxVolumeCapacity);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
