/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef OSXVOLUMETABLE_H
#define OSXVOLUMETABLE_H

/* function declarations */
void init_osxVolumeTable(void);
void initialize_table_osxVolumeTable(void);
Netsnmp_Node_Handler osxVolumeTable_handler;
Netsnmp_First_Data_Point  osxVolumeTable_get_first_data_point;
Netsnmp_Next_Data_Point   osxVolumeTable_get_next_data_point;

/* column number definitions for table osxVolumeTable */
       #define COLUMN_OSXVOLUMEINDEX		1
       #define COLUMN_OSXVOLUMEFILESYSTEM		2
       #define COLUMN_OSXVOLUMEMOUNTPOINT		3
       #define COLUMN_OSXVOLUMESIZE		4
       #define COLUMN_OSXVOLUMEUSED		5
       #define COLUMN_OSXVOLUMEAVAIL		6
       #define COLUMN_OSXVOLUMECAPACITY		7
#endif /* OSXVOLUMETABLE_H */
