/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef RAM_H
#define RAM_H

/* function declarations */
void init_ram(void);
Netsnmp_Node_Handler handle_ram;

#endif /* RAM_H */
