/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef XSANVOLUMETABLE_H
#define XSANVOLUMETABLE_H

/* function declarations */
void init_xsanVolumeTable(void);
void initialize_table_xsanVolumeTable(void);
Netsnmp_Node_Handler xsanVolumeTable_handler;
Netsnmp_First_Data_Point  xsanVolumeTable_get_first_data_point;
Netsnmp_Next_Data_Point   xsanVolumeTable_get_next_data_point;

/* column number definitions for table xsanVolumeTable */
       #define COLUMN_XSANVOLUMEINDEX		1
       #define COLUMN_XSANVOLUMECREATED		2
       #define COLUMN_XSANVOLUMEACTIVECONNECTIONS		3
       #define COLUMN_XSANVOLUMEFSBLOCKSIZE		4
       #define COLUMN_XSANVOLUMEMSGBUFFERSIZE		5
       #define COLUMN_XSANVOLUMEDISKDEVICES		6
       #define COLUMN_XSANVOLUMESTRIPEGROUPS		7
       #define COLUMN_XSANVOLUMETOTALKBLOCKS		8
       #define COLUMN_XSANVOLUMEFREEKBLOCKS		9
       #define COLUMN_XSANVOLUMETOTALBLOCKS		10
       #define COLUMN_XSANVOLUMEFREEBLOCKS		11
       #define COLUMN_XSANVOLUMEFREEBLOCKS		11
#endif /* XSANVOLUMETABLE_H */
