/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xsanVolumeTable.h"

/** Initializes the xsanVolumeTable module */
void
init_xsanVolumeTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_xsanVolumeTable();
}

  # Determine the first/last column names

/** Initialize the xsanVolumeTable table by defining its contents and how it's structured */
void
initialize_table_xsanVolumeTable(void)
{
    static oid xsanVolumeTable_oid[] = {1,3,6,1,4,1,20038,2,1,1,1};
    size_t xsanVolumeTable_oid_len   = OID_LENGTH(xsanVolumeTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "xsanVolumeTable",     xsanVolumeTable_handler,
              xsanVolumeTable_oid, xsanVolumeTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: xsanVolumeIndex */
                           0);
    table_info->min_column = COLUMN_XSANVOLUMEINDEX;
    table_info->max_column = COLUMN_XSANVOLUMEFREEBLOCKS;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = xsanVolumeTable_get_first_data_point;
    iinfo->get_next_data_point  = xsanVolumeTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct xsanVolumeTable_entry {
    /* Index values */
    long xsanVolumeIndex;

    /* Column values */
    char *xsanVolumeCreated;
    size_t xsanVolumeCreated_len;
    u_long xsanVolumeActiveConnections;
    u_long xsanVolumeFsBlockSize;
    u_long xsanVolumeMsgBufferSize;
    u_long xsanVolumeDiskDevices;
    u_long xsanVolumeStripeGroups;
    u_long xsanVolumeTotalKBlocks;
    u_long xsanVolumeFreeKBlocks;
    U64 xsanVolumeTotalBlocks;
    U64 xsanVolumeFreeBlocks;
    U64 xsanVolumeFreeBlocks;

    /* Illustrate using a simple linked list */
    int   valid;
    struct xsanVolumeTable_entry *next;
};

struct xsanVolumeTable_entry  *xsanVolumeTable_head;

/* create a new row in the (unsorted) table */
struct xsanVolumeTable_entry *
xsanVolumeTable_createEntry(
                 long  xsanVolumeIndex,
                ) {
    struct xsanVolumeTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct xsanVolumeTable_entry);
    if (!entry)
        return NULL;

    entry->xsanVolumeIndex = xsanVolumeIndex;
    entry->next = xsanVolumeTable_head;
    xsanVolumeTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
xsanVolumeTable_removeEntry( struct xsanVolumeTable_entry *entry ) {
    struct xsanVolumeTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = xsanVolumeTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        xsanVolumeTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
xsanVolumeTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = xsanVolumeTable_head;
    return xsanVolumeTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
xsanVolumeTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct xsanVolumeTable_entry *entry = (struct xsanVolumeTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->xsanVolumeIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the xsanVolumeTable table */
int
xsanVolumeTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct xsanVolumeTable_entry          *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct xsanVolumeTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_XSANVOLUMEINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->xsanVolumeIndex);
                break;
            case COLUMN_XSANVOLUMECREATED:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->xsanVolumeCreated,
                                          table_entry->xsanVolumeCreated_len);
                break;
            case COLUMN_XSANVOLUMEACTIVECONNECTIONS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->xsanVolumeActiveConnections);
                break;
            case COLUMN_XSANVOLUMEFSBLOCKSIZE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->xsanVolumeFsBlockSize);
                break;
            case COLUMN_XSANVOLUMEMSGBUFFERSIZE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->xsanVolumeMsgBufferSize);
                break;
            case COLUMN_XSANVOLUMEDISKDEVICES:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->xsanVolumeDiskDevices);
                break;
            case COLUMN_XSANVOLUMESTRIPEGROUPS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->xsanVolumeStripeGroups);
                break;
            case COLUMN_XSANVOLUMETOTALKBLOCKS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->xsanVolumeTotalKBlocks);
                break;
            case COLUMN_XSANVOLUMEFREEKBLOCKS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->xsanVolumeFreeKBlocks);
                break;
            case COLUMN_XSANVOLUMETOTALBLOCKS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER64,
                                            table_entry->xsanVolumeTotalBlocks);
                break;
            case COLUMN_XSANVOLUMEFREEBLOCKS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER64,
                                            table_entry->xsanVolumeFreeBlocks);
                break;
            case COLUMN_XSANVOLUMEFREEBLOCKS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER64,
                                            table_entry->xsanVolumeFreeBlocks);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
