/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef FSTABLE_H
#define FSTABLE_H

/* function declarations */
void init_fsTable(void);
void initialize_table_fsTable(void);
Netsnmp_Node_Handler fsTable_handler;
Netsnmp_First_Data_Point  fsTable_get_first_data_point;
Netsnmp_Next_Data_Point   fsTable_get_next_data_point;

/* column number definitions for table fsTable */
       #define COLUMN_FSINDEX		1
       #define COLUMN_FSFILESYSTEM		2
       #define COLUMN_FSMOUNTPOINT		3
       #define COLUMN_FSSIZE		4
       #define COLUMN_FSUSED		5
       #define COLUMN_FSAVAIL		6
       #define COLUMN_FSUTILIZATION		7
       #define COLUMN_FSWRITEABLE 8
       #define COLUMN_FSREMOVABLE 9
       #define COLUMN_FSBOOTABLE 10
       #define COLUMN_FSSMARTSTATUS 11
       #define COLUMN_FSSMARTMESSAGE 12
#endif /* FSTABLE_H */
