/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef RAIDSETTABLE_H
#define RAIDSETTABLE_H

/* function declarations */
void init_raidSetTable(void);
void initialize_table_raidSetTable(void);
Netsnmp_Node_Handler raidSetTable_handler;
Netsnmp_First_Data_Point  raidSetTable_get_first_data_point;
Netsnmp_Next_Data_Point   raidSetTable_get_next_data_point;

/* column number definitions for table raidSetTable */
       #define COLUMN_RAIDSETINDEX		1
       #define COLUMN_RAIDSETNAME		2
       #define COLUMN_RAIDSETTYPE		3
       #define COLUMN_RAIDSETSIZE		4
       #define COLUMN_RAIDSETUNUSED		5
       #define COLUMN_RAIDSETCOMMENTS		6
#endif /* RAIDSETTABLE_H */

    /* Typical data structure for a row entry */
struct raidSetTable_entry {
    /* Index values */
    long raidSetIndex;

    /* Column values */
    char *raidSetName;
    size_t raidSetName_len;
    char *raidSetType;
    size_t raidSetType_len;
    uint32_t raidSetSize;
    uint32_t raidSetUnused;
    char *raidSetComments;
    size_t raidSetComments_len;

    /* Obsolscence check */
    time_t last_seen;

    /* Illustrate using a simple linked list */
    int   valid;
    struct raidSetTable_entry *next;
};

struct raidSetTable_entry* raidSetTable_get_head();
