/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef RAIDINFO_H
#define RAIDINFO_H

/* function declarations */
void init_raidInfo(void);
Netsnmp_Node_Handler handle_raidGeneralStatus;
Netsnmp_Node_Handler handle_raidGeneralStatusMessage;
Netsnmp_Node_Handler handle_raidBatteryStatus;
Netsnmp_Node_Handler handle_raidBatteryStatusMessage;
Netsnmp_Node_Handler handle_raidHardwareVersion;
Netsnmp_Node_Handler handle_raidFirmwareVersion;
Netsnmp_Node_Handler handle_raidWriteCache;

#endif /* RAIDINFO_H */
