/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef RAIDDRIVETABLE_H
#define RAIDDRIVETABLE_H

/* function declarations */
void init_raidDriveTable(void);
void initialize_table_raidDriveTable(void);
Netsnmp_Node_Handler raidDriveTable_handler;
Netsnmp_First_Data_Point  raidDriveTable_get_first_data_point;
Netsnmp_Next_Data_Point   raidDriveTable_get_next_data_point;

/* column number definitions for table raidDriveTable */
       #define COLUMN_RAIDDRIVEINDEX		1
       #define COLUMN_RAIDDRIVELOCATION		2
       #define COLUMN_RAIDDRIVESETNAME		3
       #define COLUMN_RAIDDRIVESIZE		4
       #define COLUMN_RAIDDRIVESTATUS		5
       #define COLUMN_RAIDDRIVESTATUSMESSAGE		6
       #define COLUMN_RAIDDRIVESETINDEX		7
#endif /* RAIDDRIVETABLE_H */
