/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef RAIDVOLUMETABLE_H
#define RAIDVOLUMETABLE_H

/* function declarations */
void init_raidVolumeTable(void);
void initialize_table_raidVolumeTable(void);
Netsnmp_Node_Handler raidVolumeTable_handler;
Netsnmp_First_Data_Point  raidVolumeTable_get_first_data_point;
Netsnmp_Next_Data_Point   raidVolumeTable_get_next_data_point;

/* column number definitions for table raidVolumeTable */
       #define COLUMN_RAIDVOLUMEINDEX		1
       #define COLUMN_RAIDVOLUMENAME		2
       #define COLUMN_RAIDVOLUMESETNAME		3
       #define COLUMN_RAIDVOLUMETYPE		4
       #define COLUMN_RAIDVOLUMESIZE		5
       #define COLUMN_RAIDVOLUMESTATUS		6
       #define COLUMN_RAIDVOLUMESTATUSMESSAGE		7
       #define COLUMN_RAIDVOLUMECOMMENTS		8
       #define COLUMN_RAIDVOLUMESETINDEX		9
#endif /* RAIDVOLUMETABLE_H */
