/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "raidVolumeTable.h"

/** Initializes the raidVolumeTable module */
void
init_raidVolumeTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_raidVolumeTable();
}

  # Determine the first/last column names

/** Initialize the raidVolumeTable table by defining its contents and how it's structured */
void
initialize_table_raidVolumeTable(void)
{
    static oid raidVolumeTable_oid[] = {1,3,6,1,4,1,20038,2,1,6,4};
    size_t raidVolumeTable_oid_len   = OID_LENGTH(raidVolumeTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "raidVolumeTable",     raidVolumeTable_handler,
              raidVolumeTable_oid, raidVolumeTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: raidVolumeIndex */
                           0);
    table_info->min_column = COLUMN_RAIDVOLUMENAME;
    table_info->max_column = COLUMN_RAIDVOLUMESETINDEX;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = raidVolumeTable_get_first_data_point;
    iinfo->get_next_data_point  = raidVolumeTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct raidVolumeTable_entry {
    /* Index values */
    long raidVolumeIndex;

    /* Column values */
    char raidVolumeName[NNN];
    size_t raidVolumeName_len;
    char raidVolumeSetName[NNN];
    size_t raidVolumeSetName_len;
    char raidVolumeType[NNN];
    size_t raidVolumeType_len;
    u_long raidVolumeSize;
    long raidVolumeStatus;
    char raidVolumeStatusMessage[NNN];
    size_t raidVolumeStatusMessage_len;
    char raidVolumeComments[NNN];
    size_t raidVolumeComments_len;
    long raidVolumeSetIndex;

    /* Illustrate using a simple linked list */
    int   valid;
    struct raidVolumeTable_entry *next;
};

struct raidVolumeTable_entry  *raidVolumeTable_head;

/* create a new row in the (unsorted) table */
struct raidVolumeTable_entry *
raidVolumeTable_createEntry(
                 long  raidVolumeIndex,
                ) {
    struct raidVolumeTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct raidVolumeTable_entry);
    if (!entry)
        return NULL;

    entry->raidVolumeIndex = raidVolumeIndex;
    entry->next = raidVolumeTable_head;
    raidVolumeTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
raidVolumeTable_removeEntry( struct raidVolumeTable_entry *entry ) {
    struct raidVolumeTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = raidVolumeTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        raidVolumeTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
raidVolumeTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = raidVolumeTable_head;
    return raidVolumeTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
raidVolumeTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct raidVolumeTable_entry *entry = (struct raidVolumeTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->raidVolumeIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the raidVolumeTable table */
int
raidVolumeTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct raidVolumeTable_entry          *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct raidVolumeTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RAIDVOLUMENAME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->raidVolumeName,
                                          table_entry->raidVolumeName_len);
                break;
            case COLUMN_RAIDVOLUMESETNAME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->raidVolumeSetName,
                                          table_entry->raidVolumeSetName_len);
                break;
            case COLUMN_RAIDVOLUMETYPE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->raidVolumeType,
                                          table_entry->raidVolumeType_len);
                break;
            case COLUMN_RAIDVOLUMESIZE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->raidVolumeSize);
                break;
            case COLUMN_RAIDVOLUMESTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->raidVolumeStatus);
                break;
            case COLUMN_RAIDVOLUMESTATUSMESSAGE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->raidVolumeStatusMessage,
                                          table_entry->raidVolumeStatusMessage_len);
                break;
            case COLUMN_RAIDVOLUMECOMMENTS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->raidVolumeComments,
                                          table_entry->raidVolumeComments_len);
                break;
            case COLUMN_RAIDVOLUMESETINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->raidVolumeSetIndex);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
