/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xsanVolumeTable.h"
#include "xsanStripeGroupTable.h"
#include "xsanAffinityTable.h"
#include "util.h"

static struct timeval affinity_cache_timestamp = { 0, 0 };
#define MAX_CACHE_AGE 90

/** Initializes the xsanAffinityTable module */
void
init_xsanAffinityTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_xsanAffinityTable();
}

/** Initialize the xsanAffinityTable table by defining its contents and how it's structured */
void
initialize_table_xsanAffinityTable(void)
{
    static oid xsanAffinityTable_oid[] = {1,3,6,1,4,1,20038,2,1,1,4};
    size_t xsanAffinityTable_oid_len   = OID_LENGTH(xsanAffinityTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "xsanAffinityTable",     xsanAffinityTable_handler,
              xsanAffinityTable_oid, xsanAffinityTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: xsanVolumeIndex */
                           ASN_INTEGER,  /* index: xsanAffinityIndex */
                           0);
    table_info->min_column = COLUMN_XSANAFFINITYINDEX;
    table_info->max_column = COLUMN_XSANAFFINITYUSEDMBYTES;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = xsanAffinityTable_get_first_data_point;
    iinfo->get_next_data_point  = xsanAffinityTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct xsanAffinityTable_entry {
    /* Index values */
    long xsanVolumeIndex;
    long xsanAffinityIndex;

    /* Column values */
    char *xsanAffinityName;
    size_t xsanAffinityName_len;
    long xsanAffinityStripeGroups;
    u_long xsanAffinityTotalKBlocks;
    u_long xsanAffinityFreeKBlocks;
    U64 xsanAffinityTotalBlocks;
    U64 xsanAffinityFreeBlocks;
    u_long xsanAffinityUtilization;
    u_long xsanAffinityTotalMBytes;
    u_long xsanAffinityFreeMBytes;
    u_long xsanAffinityUsedMBytes;

    /* Illustrate using a simple linked list */
    int   valid;
    struct xsanAffinityTable_entry *next;
};

struct xsanAffinityTable_entry  *xsanAffinityTable_head;
static int last_index = 0;

/* create a new row in the (unsorted) table */
struct xsanAffinityTable_entry *
xsanAffinityTable_createEntry(long  xsanVolumeIndex) 
{
    struct xsanAffinityTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct xsanAffinityTable_entry);
    if (!entry)
        return NULL;

    last_index++;
    entry->xsanVolumeIndex = xsanVolumeIndex;
    entry->xsanAffinityIndex = last_index;
    entry->next = xsanAffinityTable_head;
    xsanAffinityTable_head = entry;
    
    affinity_cache_timestamp.tv_sec = 0;
    affinity_cache_timestamp.tv_usec = 0;
    
    return entry;
}

/* remove a row from the table */
void
xsanAffinityTable_removeEntry( struct xsanAffinityTable_entry *entry ) {
    struct xsanAffinityTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = xsanAffinityTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        xsanAffinityTable_head = ptr->next;
    else
        prev->next = ptr->next;
        
      if (entry->xsanAffinityName) free(entry->xsanAffinityName);

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}

long find_or_create_affinity_index (long volumeIndex, char *affinityKey)
{
    struct xsanAffinityTable_entry *entry = xsanAffinityTable_head;
    while (entry)
    {
        if (entry->xsanVolumeIndex == volumeIndex && !strcmp(entry->xsanAffinityName, affinityKey)) break;
        entry = entry->next;
    }
    if (!entry)
    {
        entry = xsanAffinityTable_createEntry(volumeIndex);
        entry->xsanAffinityName = strdup(affinityKey);
        entry->xsanAffinityName_len = strlen(affinityKey);
    }
    return entry->xsanAffinityIndex;
}

/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
xsanAffinityTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = xsanAffinityTable_head;
    return xsanAffinityTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
xsanAffinityTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct xsanAffinityTable_entry *entry = (struct xsanAffinityTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->xsanVolumeIndex );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->xsanAffinityIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}

extern struct xsanStripeGroupTable_entry  *xsanStripeGroupTable_head;

void update_affinities()
{
    struct xsanAffinityTable_entry *entry = xsanAffinityTable_head;
    while (entry)
    {
        /* Zero the counters */
        entry->xsanAffinityStripeGroups = 0;
        entry->xsanAffinityTotalKBlocks = 0;
        entry->xsanAffinityFreeKBlocks = 0;
        entry->xsanAffinityTotalBlocks.high = 0;
        entry->xsanAffinityTotalBlocks.low = 0;
        entry->xsanAffinityFreeBlocks.high = 0;
        entry->xsanAffinityFreeBlocks.low = 0;
        entry->xsanAffinityUtilization = 0;
        entry->xsanAffinityTotalMBytes = 0;
        entry->xsanAffinityFreeMBytes = 0;
        entry->xsanAffinityUsedMBytes = 0;
        
        /* Loop through stripe groups */
        struct xsanStripeGroupTable_entry *stripeGroup = xsanStripeGroupTable_head;
        while (stripeGroup)
        {
            if (stripeGroup->xsanAffinityIndex == entry->xsanAffinityIndex)
            {
                /* Stripe Group is a member of this affinity */
                entry->xsanAffinityStripeGroups++;
                entry->xsanAffinityTotalKBlocks += stripeGroup->xsanStripeGroupTotalKBlocks;
                entry->xsanAffinityFreeKBlocks += stripeGroup->xsanStripeGroupFreeKBlocks;
                entry->xsanAffinityTotalBlocks = sum_U64(entry->xsanAffinityTotalBlocks, stripeGroup->xsanStripeGroupTotalBlocks);
                entry->xsanAffinityFreeBlocks = sum_U64(entry->xsanAffinityFreeBlocks, stripeGroup->xsanStripeGroupFreeBlocks);
                
                u_long blockSize = blockSizeForVolumeIndex(stripeGroup->xsanVolumeIndex);
                entry->xsanAffinityTotalMBytes += stripeGroup->xsanStripeGroupTotalKBlocks * blockSize;   // Both are in K units, and multiply to M -- same for the next two
                entry->xsanAffinityFreeMBytes += stripeGroup->xsanStripeGroupFreeKBlocks * blockSize;
                entry->xsanAffinityUsedMBytes += (stripeGroup->xsanStripeGroupTotalKBlocks - stripeGroup->xsanStripeGroupFreeKBlocks) * blockSize;
            }
            
            /* Move to next */
            stripeGroup = stripeGroup->next;
        }
        
        /* Update utilization */
        entry->xsanAffinityUtilization = (u_long) (((double) (entry->xsanAffinityTotalKBlocks - entry->xsanAffinityFreeKBlocks) / (double) entry->xsanAffinityTotalKBlocks) * 100.0);
        
        /* Move to next */
        entry = entry->next;
    }
}

void update_affinities_if_necessary ()
{
    struct timeval now;
    gettimeofday (&now, NULL);
    if ((now.tv_sec - affinity_cache_timestamp.tv_sec) > MAX_CACHE_AGE) update_affinities();
}

/** handles requests for the xsanAffinityTable table */
int
xsanAffinityTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct xsanAffinityTable_entry          *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct xsanAffinityTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
            
            update_affinities_if_necessary();
    
            switch (table_info->colnum) {
            case COLUMN_XSANVOLUMEINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->xsanVolumeIndex);
                break;
            case COLUMN_XSANAFFINITYINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->xsanAffinityIndex);
                break;
            case COLUMN_XSANAFFINITYNAME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->xsanAffinityName,
                                          table_entry->xsanAffinityName_len);
                break;
            case COLUMN_XSANAFFINITYSTRIPEGROUPS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->xsanAffinityStripeGroups);
                break;
            case COLUMN_XSANAFFINITYTOTALKBLOCKS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->xsanAffinityTotalKBlocks);
                break;
            case COLUMN_XSANAFFINITYFREEKBLOCKS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->xsanAffinityFreeKBlocks);
                break;
            case COLUMN_XSANAFFINITYTOTALBLOCKS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_COUNTER64,
                                            (u_char *)&table_entry->xsanAffinityTotalBlocks, sizeof(U64));
                break;
            case COLUMN_XSANAFFINITYFREEBLOCKS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_COUNTER64,
                                            (u_char *)&table_entry->xsanAffinityFreeBlocks, sizeof(U64));
                break;
            case COLUMN_XSANAFFINITYUTILIZATION:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->xsanAffinityUtilization);
                break;
            case COLUMN_XSANAFFINITYTOTALMBYTES:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->xsanAffinityTotalMBytes);
                break;
            case COLUMN_XSANAFFINITYFREEMBYTES:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->xsanAffinityFreeMBytes);
                break;
            case COLUMN_XSANAFFINITYUSEDMBYTES:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_GAUGE,
                                            table_entry->xsanAffinityUsedMBytes);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
