/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "xsanNodeTable.h"
#include <pcre.h>
#include "log.h"
#include "util.h"

#define OVECCOUNT 90

/** Initializes the xsanNodeTable module */
void
init_xsanNodeTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_xsanNodeTable();
}

/** Initialize the xsanNodeTable table by defining its contents and how it's structured */
void
initialize_table_xsanNodeTable(void)
{
    static oid xsanNodeTable_oid[] = {1,3,6,1,4,1,20038,2,1,1,3};
    size_t xsanNodeTable_oid_len   = OID_LENGTH(xsanNodeTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "xsanNodeTable",     xsanNodeTable_handler,
              xsanNodeTable_oid, xsanNodeTable_oid_len,
              HANDLER_CAN_RONLY
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: xsanVolumeIndex */
                           ASN_INTEGER,  /* index: xsanStripeGroupIndex */
                           ASN_INTEGER,  /* index: xsanNodeIndex */
                           0);
    table_info->min_column = COLUMN_XSANNODEINDEX;
    table_info->max_column = COLUMN_XSANNODENAME;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = xsanNodeTable_get_first_data_point;
    iinfo->get_next_data_point  = xsanNodeTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct xsanNodeTable_entry {
    /* Index values */
    long xsanVolumeIndex;
    long xsanStripeGroupIndex;
    long xsanNodeIndex;

    /* Column values */
    char *xsanNodeName;
    size_t xsanNodeName_len;
    
    /* Obsolescence */
    time_t last_seen;

    /* Illustrate using a simple linked list */
    int   valid;
    struct xsanNodeTable_entry *next;
};

struct xsanNodeTable_entry  *xsanNodeTable_head;

/* create a new row in the (unsorted) table */
struct xsanNodeTable_entry *
xsanNodeTable_createEntry(
                 long  xsanVolumeIndex,
                 long  xsanStripeGroupIndex,
                 long  xsanNodeIndex) {
    struct xsanNodeTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct xsanNodeTable_entry);
    if (!entry)
        return NULL;

    entry->xsanVolumeIndex = xsanVolumeIndex;
    entry->xsanStripeGroupIndex = xsanStripeGroupIndex;
    entry->xsanNodeIndex = xsanNodeIndex;
    entry->next = xsanNodeTable_head;
    xsanNodeTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
xsanNodeTable_removeEntry( struct xsanNodeTable_entry *entry ) {
    struct xsanNodeTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = xsanNodeTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        xsanNodeTable_head = ptr->next;
    else
      prev->next = ptr->next;

    if (entry->xsanNodeName) free(entry->xsanNodeName);

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
xsanNodeTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = xsanNodeTable_head;
    return xsanNodeTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
xsanNodeTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct xsanNodeTable_entry *entry = (struct xsanNodeTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->xsanVolumeIndex );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->xsanStripeGroupIndex );
        idx = idx->next_variable;
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->xsanNodeIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}

void update_nodes(char *data, size_t data_len, long volumeIndex, long stripeGroupIndex)
{
    struct timeval now;
    gettimeofday (&now, NULL);

    const char *error;
    int erroffset;
    int ovector[OVECCOUNT];
    pcre *re = pcre_compile("^[ ]*Node (\\d+) \\[(.*)\\]", PCRE_MULTILINE, &error, &erroffset, NULL);

    if (re == NULL) { x_printf ("update_nodes failed to compile regex"); return; }

    ovector[0] = 0;
    ovector[1] = 0;
    while(1)
    {
        int options = 0;                 /* Normally no options */
        int start_offset = ovector[1];   /* Start at end of previous match */

        if (ovector[0] == ovector[1])
        {
            if (ovector[0] == (int)data_len) break;
        }

        int rc = pcre_exec(
                            re,                   /* the compiled pattern */
                            NULL,                 /* no extra data - we didn't study the pattern */
                            data,              /* the subject string */
                            data_len,       /* the length of the subject */
                            start_offset,         /* starting offset in the subject */
                            options,              /* options */
                            ovector,              /* output vector for substring information */
                            OVECCOUNT);           /* number of elements in the output vector */

        x_printf ("update_nodes rc=%i", rc);

        if (rc == PCRE_ERROR_NOMATCH)
        {
            x_printf ("update_nodes No match");
            if (options == 0) break;
            ovector[1] = start_offset + 1;
            continue;    /* Go round the loop again */
        }

        /* Other matching errors are not recoverable. */
        if (rc > 0)
        {
            /* Matched an Xsan Stripe Group. Vectors: 
             *    0 = Full text match for stripe group
             *    1(2) = Node Index (assigned by cvadmin)
             *    2(4) = Node Name
             */
             
             printf ("Node: '%.*s'\n", ovector[1] - ovector[0], data + ovector[0]);
                          
            long nodeIndex = extract_uint_in_range (data + ovector[2], ovector[3] - ovector[2]);

            struct xsanNodeTable_entry *entry = xsanNodeTable_head;
            while (entry)
            {
                if (entry->xsanVolumeIndex == volumeIndex && entry->xsanStripeGroupIndex == stripeGroupIndex && entry->xsanNodeIndex == nodeIndex) break;
                entry = entry->next;
            }
            if (!entry)
            {
                entry = xsanNodeTable_createEntry (volumeIndex, stripeGroupIndex, nodeIndex);
            }
            entry->last_seen = now.tv_sec;
            
            extract_string_in_range (data + ovector[4], ovector[5] - ovector[4], &entry->xsanNodeName, &entry->xsanNodeName_len);
        }
        else
        {
            x_printf("Matching error %d\n", rc);
            pcre_free(re);    /* Release memory used for the compiled pattern */
            return;
        }  
    }    
    
    pcre_free(re);    /* Release memory used for the compiled pattern */
    
    /* Obsolescence Checking */
    struct xsanNodeTable_entry *entry = xsanNodeTable_head;
    while (entry)
    {
        struct xsanNodeTable_entry *next = entry->next;
        if (entry->xsanVolumeIndex == volumeIndex && entry->xsanStripeGroupIndex == stripeGroupIndex && entry->last_seen != now.tv_sec)
        {
            /* Entry is obsolete */
            xsanNodeTable_removeEntry(entry);
        }
        entry = next;
    }
    
}

/** handles requests for the xsanNodeTable table */
int
xsanNodeTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct xsanNodeTable_entry          *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct xsanNodeTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_XSANVOLUMEINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->xsanVolumeIndex);
                break;
            case COLUMN_XSANNODENAME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->xsanNodeName,
                                          table_entry->xsanNodeName_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}
